[package]
name = "silicium"
version = "0.1.0"
edition = "2021"

[dependencies]
x86_64 = { git = "https://github.com/haoud/silicium-x86_64", package = "silicium-x86_64" }
sync = { git = "https://github.com/haoud/silicium-sync", package = "silicium-sync" }

linked_list_allocator = "0.10.4"
bitfield = "0.14.0"
bitflags = "1.3.2"
limine = "0.1.10"
log = "0.4.17"

[[bin]]
name = "silicium"
test = true
bench = false