[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["alloc", "core", "compiler_builtins"]

[build]
target = "build/x86_64.json"

[target.'cfg(target_os = "none")']
runner = "scripts/runner.sh"
